services:
  postgres:
    image: postgres:16
    container_name: payment-platform-postgres
    environment:
      POSTGRES_DB: payment-platform
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: