CREATE TABLE customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE ,
    status VARCHAR(20) NOT NULL ,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT chk_customer_status
        CHECK ( status IN ('ACTIVE', 'BLOCKED', 'CLOSED'))
);

CREATE TABLE account(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,
    account_number VARCHAR(10) NOT NULL UNIQUE ,
    customer_id BIGINT NOT NULL ,
    balance NUMERIC(19,2) NOT NULL  DEFAULT 0,
    status VARCHAR(20) NOT NULL ,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT fk_account_customer
        FOREIGN KEY (customer_id)
        REFERENCES customer(id),

    CONSTRAINT chk_account_balance
        CHECK ( balance >= 0 ),

    CONSTRAINT chk_account_status
        CHECK ( status IN ('ACTIVE', 'BLOCKED', 'CLOSED'))
);

CREATE TABLE transactions(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_account_id      BIGINT,
    destination_account_id BIGINT                   NOT NULL,
    amount                 NUMERIC(19, 2)           NOT NULL,
    type                   VARCHAR(20)              NOT NULL,
    status                 VARCHAR(20)              NOT NULL,
    created_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at           TIMESTAMP WITH TIME ZONE,

    CONSTRAINT fk_transactions_source_account
        FOREIGN KEY (source_account_id)
            REFERENCES account(id),

    CONSTRAINT fk_transactions_destination_account
        FOREIGN KEY (destination_account_id)
            REFERENCES account(id),

    CONSTRAINT chk_transactions_amount
        CHECK (amount > 0),

    CONSTRAINT chk_transactions_type
        CHECK (type IN ('DEPOSIT', 'TRANSFER')),

    CONSTRAINT chk_transactions_status
        CHECK (status IN ('COMPLETED', 'FAILED')),

    CONSTRAINT chk_transactions_different_accounts
        CHECK (
            source_account_id IS NULL
                OR source_account_id <> destination_account_id
            ),

    CONSTRAINT chk_transactions_type_source
        CHECK (
            (type = 'DEPOSIT' AND source_account_id IS NULL)
                OR
            (type = 'TRANSFER' AND source_account_id IS NOT NULL)
            )
);

    CREATE INDEX idx_transactions_source_account
        ON transactions(source_account_id);

    CREATE INDEX idx_transactions_destination_account
        ON transactions(destination_account_id);